### ISSUE TITLE
RCV - Fails when using hashtag with onClick prop with SSR

### ISSUE THREAD

**Issue by oded-soffrin** [wix-incubator/rich-content#130]
See example on sep6-viewer-ssr branch
there are a text line and hashtag with decorator
the gallery below doesn't render due to a client-side exception: "Uncaught Error: Unable to find element with ID 29."

if we remove the 'onClick' on the hashtag, everything works

**Comment by oded-soffrin** [comment]
@audriusk-wix FYI
(blocker for blog app)

**Comment by lxgreen** [comment]
[#134](https://github.com/wix-incubator/rich-content/pull/134) fixed
