### ISSUE TITLE
Headers with mix styling are broken into blocks

### ISSUE THREAD

**Issue by muteor** [wix-incubator/rich-content#185]
This is very much related to #184 by the looks of it.

Reproduction steps:

- Type "Cat Dog Frog"
- Highlight it all -- click the Title (T) icon
- Then highlight "Dog"
- Italicize, bold, or underline "Dog"
- Heading is broken onto three lines

![image](https://user-images.githubusercontent.com/305164/48201334-c3b7d780-e359-11e8-848c-fa531edf9cf9.png)

**Comment by lxgreen** [comment]
note: this bug is caused by inline headers/other inline styles interference. to solve this, we should remove the standard inline-style mapping, and provide the new mapping considering the inline headers

**Comment by muteor** [comment]
This looks like it was fixed, thanks!
