### ISSUE TITLE
`textToolbarType="static"` is not showing any toolbar at all

### ISSUE THREAD

**Issue by mastertheblaster** [wix-incubator/rich-content#20]
<img width="868" alt="screen shot 2018-04-25 at 17 41 11" src="https://user-images.githubusercontent.com/10008149/39253155-dcf7d096-48af-11e8-852a-3d5debb78d24.png">

**Comment by bchmn** [comment]
you are responsible of rendering the toolbar, here's how we do it in the example:
https://github.com/wix-incubator/rich-content/blob/master/packages/editor-example/src/App.jsx#L160
https://github.com/wix-incubator/rich-content/blob/master/packages/editor-example/src/App.jsx#L268
