### ISSUE TITLE
Optimize bundle size for Viewer

### ISSUE THREAD

**Issue by sarunas** [wix-incubator/rich-content#207]
Adding Webpack Analyzer screenshot to see the issue.
<img width="367" alt="capturfiles_15" src="https://user-images.githubusercontent.com/250523/50073581-b5bf6700-01e1-11e9-9032-09d29e88ad27.png">

Things to be done:
- externalize lodash
- check if `wix-rich-content-common` is really needed
- check why does `entities`, `htmlparser2` and `react-tooltip` packages needed

**Comment by vybu** [comment]
we have externalized lodash ourselves.

**Comment by lxgreen** [comment]
![image](https://user-images.githubusercontent.com/4170342/70752875-30ab5700-1d3c-11ea-90f0-950bca2a73fe.png)
