### ISSUE TITLE
Block Deletion bug

### ISSUE THREAD

**Issue by muteor** [wix-incubator/rich-content#219]
When deleting an atomic (image plugin in this case) using backspace the editors selection state becomes corrupt.

Here is video of how to reproduce:

![deletionbug](https://user-images.githubusercontent.com/305164/50725431-6a6bea80-10f5-11e9-934f-8a5f16de138a.gif)

Steps:
- Enter text
- Add image
- Enter text
- Select image press backspace
- move cursor to end of last line press return and type more

My guess is that its a bug in the way removeBlock works:

https://github.com/wix-incubator/rich-content/blob/bf7b2a84cfb414938ec716e3a7dac3caef4b3508/packages/editor/src/RichContentEditor/handleKeyCommand.js#L29

https://github.com/wix-incubator/rich-content/blob/3f6240232444b67af7b9948a9cdc90b6bf4be0f7/packages/common/src/Utils/draftUtils.js#L88

One thing I have found is that when working with blocks its easier to merge the blockMap into the contentState and leave the selection alone, every time I touch selection state I seem to end up with these strange corruptions :)

**Comment by bchmn** [comment]
Fixed https://github.com/wix-incubator/rich-content/pull/220
