### ISSUE TITLE
Incorrect UI state for "Open link in a new tab"

### ISSUE THREAD

**Issue by vybu** [wix-incubator/rich-content#252]
![screenshot from 2019-02-11 16-19-12](https://user-images.githubusercontent.com/6137511/52569008-e81fc600-2e18-11e9-851a-86ce3bc5b455.png)

`anchorTarget="_blank"` is passed as props, the checkbox should be checked.

When you publish behavior is correct, and when you edit you see checkbox checked, it's only when adding initially the UI state is incorrect.

**Comment by oded-soffrin** [comment]
fixed in 6.7.0
