### ISSUE TITLE
Giphy does not pass theme

### ISSUE THREAD

**Issue by muteor** [wix-incubator/rich-content#257]
https://github.com/wix-incubator/rich-content/blob/master/packages/plugin-giphy/src/giphy-component.jsx

When rendering the viewer it should pass theme to the viewer so styles can be applied.

**Comment by lxgreen** [comment]
The `giphy-viewer` gets the theme via context: https://github.com/wix-incubator/rich-content/blob/fcb95244a98a611a1db6244259f7d6960b924035/packages/plugin-giphy/web/src/giphy-viewer.jsx#L37
