### ISSUE TITLE
Some Giphy plugin icons are not themable

### ISSUE THREAD

**Issue by artur-charcenko** [wix-incubator/rich-content#323]
All colors of these icons are hardcoded:
https://github.com/wix-incubator/rich-content/blob/master/packages/plugin-giphy/src/icons/SearchIcon.jsx
https://github.com/wix-incubator/rich-content/blob/master/packages/plugin-giphy/src/icons/CloseIcon.jsx

**Comment by lxgreen** [comment]
[fix](https://github.com/wix-incubator/rich-content/pull/361)
