### ISSUE TITLE
Demo site: editor toolbar too tall

### ISSUE THREAD

**Issue by tomByrer** [wix-incubator/rich-content#383]
The wrapper div for the toolbar is too tall.  "First line" in screenshot shows where the actual text editing starts.  I understand that you might not be using a 4k monitor like me.  B)

Sorry, seems screen shot Firefox dev tool highlight won't work, so I drew a square around the toolbar div:

![wix-editor-toolbar-too-large](https://user-images.githubusercontent.com/1308419/64489685-92c75e00-d21b-11e9-9e07-20a5f13bcd88.png)

Thanks for your editor; might use it on a project someday.

**Comment by lxgreen** [comment]
Hi Tom,

Thanks for your report. Can you please provide the details regarding the browser, OS and screen resolution?

Also, did you apply the Static Toolbar in settings?

**Comment by lxgreen** [comment]
fixed
