### ISSUE TITLE
Bug: file upload spinner animation is not applied

### ISSUE THREAD

**Issue by summercrane** [wix-incubator/rich-content#415]
File upload spinner is not active. Problem that generated css file has an animation, which has names with applied suffixes '-ltr' and '-rtr'. The spinner class uses animation name, which has no suffixes therefore no animation is found and played.

![Screenshot 2019-10-16 at 12 30 55](https://user-images.githubusercontent.com/6427408/66906712-d1b5b400-f010-11e9-8299-cbadfc4ff4b7.png)

**Comment by summercrane** [comment]
![code](https://user-images.githubusercontent.com/6427408/66907317-d0d15200-f011-11e9-8fe3-f866e09f9e38.png)

**Comment by mharsat** [comment]
@summercrane spinner animation was fixed in #426

**Comment by mharsat** [comment]
@summercrane  spinner animation was fixed in #426
