### ISSUE TITLE
Bug: Clicking on image settings when image has not still uploaded shows blank window

### ISSUE THREAD

**Issue by summercrane** [wix-incubator/rich-content#418]
Reproducible in 5.1.9 and probably older versions.
As per title, while uploading the image and clicking on image settings button,
opens up a blank window. It's especially bad in mobile, because the window opened is fullscreen and there is no way to close it.
![Screenshot 2019-10-17 at 09 32 10](https://user-images.githubusercontent.com/6427408/66983694-d6867080-f0c1-11e9-8255-61119e4acaf6.png)

**Comment by lxgreen** [comment]
#428
