### ISSUE TITLE
`normalizeInitialState` throw exception when content entityMap empty

### ISSUE THREAD

**Issue by EdgBuc** [wix-incubator/rich-content#425]
In the database on some posts we have such content saved:
```
content:{
      blocks: [
        {
          key: 'f5fca',
          text: ' ',
          type: 'atomic',
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [
            {
              offset: 0,
              length: 1,
              key: 0,
            },
          ],
          data: {},
        },
      ],
      entityMap: {},
    }
```
in our code we need to compare content so before comparison we are using
`normalizeInitialState` which throws `TypeError: Cannot read property 'type' of undefined`
on line ` var entityType = entityMap[range.key + ''].type;`

Expected to not get an exception in this case.

**Comment by lxgreen** [comment]
thanks for the report, we'll fix this one in the next release

**Comment by lxgreen** [comment]
https://github.com/wix-incubator/rich-content/pull/436

**Comment by bchmn** [comment]
@EdgBuc do you know how this contentstate was created?  it's obviously invalid and we'd like to isolate the issue and prevent it from happening again.
