### ISSUE TITLE
Wrong top position in modalStyles

### ISSUE THREAD

**Issue by mbutsykin** [wix-incubator/rich-content#492]
`modalStyles.top` passed to `helpers.openModal` is wrong when toolbar with plugins located at the top of the page
![image](https://user-images.githubusercontent.com/846659/69637734-ea7aa600-1061-11ea-8ad3-6c1420508319.png)

GIPHY modal placement expected to be `bottom` in that case

![image](https://user-images.githubusercontent.com/846659/69637736-ec446980-1061-11ea-975f-40c80dabe5c8.png)

![image](https://user-images.githubusercontent.com/846659/69637716-e189d480-1061-11ea-9ca8-b55d7936a294.png)

**Comment by lxgreen** [comment]
fixed in #512
