### ISSUE TITLE
Customise toolbar container

### ISSUE THREAD

**Issue by muteor** [wix-incubator/rich-content#64]
We would like a way to customise the toolbar container, our use case is that we would like to add a "chevron" to the box.

![image](https://user-images.githubusercontent.com/305164/43191607-64cf2fb6-8ff3-11e8-9d56-a6f429207444.png)

![image](https://user-images.githubusercontent.com/305164/43191671-8c422d5a-8ff3-11e8-9d5c-069b0fa36847.png)

**Comment by lxgreen** [comment]
[#149](https://github.com/wix-incubator/rich-content/pull/149) fixed
