### ISSUE TITLE
Regular text after an inserted link is underlined

### ISSUE THREAD

**Issue by yury-n** [wix-incubator/rich-content#668]
When you insert a link and continue typing the text after it turns out underlined:
<img width="194" alt="Screen Shot 2020-02-10 at 10 38 01" src="https://user-images.githubusercontent.com/1035576/74218252-1998cf00-4cc3-11ea-95bd-009ea652d812.png">

**Comment by oded-soffrin** [comment]
Thanks, we'll take a look!

**Comment by oded-soffrin** [comment]
Fixed in 6.10.0

**Comment by yury-n** [comment]
great, thank you!
