### ISSUE TITLE
Inconsistent naming of componentData property

### ISSUE THREAD

**Issue by yuriibut** [wix-incubator/rich-content#70]
If I want to pass some data to button's `componentData` property I should use:

- for `InlineButtons`: `componentData`
- for `InlineButtons`: `data`

Please, make it the same

https://github.com/wix-incubator/rich-content/blob/9cacea014a0b0e6fc146918c7083669c085a5e0f/packages/common/src/Base/createBaseInsertPluginButton.jsx#L117

**Comment by lxgreen** [comment]
[fixed](https://github.com/wix-incubator/rich-content/commit/95a10dfdb0d01c5fe4b175c318051fccc471957b)
