### ISSUE TITLE
Mobile toolbar arrow button scrolls to the beginning/end, skipping buttons in th middle

### ISSUE THREAD

**Issue by lxgreen** [wix-incubator/rich-content#80]

**Comment by bchmn** [comment]
@lxgreen there should no longer be an arrow button on the mobile toolbar, do you still get one?

**Comment by bchmn** [comment]
[obsolete ](https://github.com/wix-incubator/rich-content/commit/92a8f8c4bc7080a4d11b421dbc3a2ebbe68481d8)
