### ISSUE TITLE
[handleFileSelection] native file selection and inconsistency.

### ISSUE THREAD

**Issue by audriusk-wix** [wix-incubator/rich-content#849]
First, when `helpers.handleFileSelection` is provided it is also used for `file-upload-plugin`. Adding custom implementation to bring back native file selection with `config.handleFileSelection` is overkill.
It would be nice if `file-upload-plugin` just had an option to ignore `helpers.handleFileSelection`.

Second, `image-plugin` and `gallery-plugin` are not using custom `config.handleFileSelection`  when replacing images. Only `helpers.handleFileSelection` is used for replace.

Last, `config.handleFileSelection` and `helpers.handleFileSelection` have different call signatures. It's not intuitive, took me some time to figure out "my bug".

**Comment by mharsat** [comment]
Hey @audriusk-wix and sorry for the late response.
Some parts of the API are very confusing, and I strongly suggest you to consult us when you get troubled.

You managed to find some unexpected behavior that should be blocked some time in the future.
To sum it up the recommended plugin configuration for uploading via native file selector is
```
  {
    helpers: {
	  onFilesChange: imageUploadHandler
	},
    config: {
      [VIDEO_TYPE]: {
        handleFileUpload: videoUploadHandler,
      },
      [FILE_UPLOAD_TYPE]: {
        onFileSelected: fileUploadHandler,
      },
    },
  };
```
And the recommended config for uploading via the media manager is
```
  {
    helpers: {
	  handleFileSelection: imageUploadHandler
	},
    config: {
      [VIDEO_TYPE]: {
        handleFileSelection: videoUploadHandler,
      },
      [FILE_UPLOAD_TYPE]: {
        handleFileSelection: fileUploadHandler,
      },
    },
  };
```
Image and gallery plugins are both handled with a single function.
Supplying a `handleFileSelection` function will override the plugin's native file selector handler (e.g. for images - `handleFileSelection` overrides `onFilesChange`).
Please refer to `Editor.js` and `EditorPlugins.js` for examples.

Following this pattern will resolve your first and second points.

Regarding the third point, as `helpers` should handles images and `config['SOME_PLUGIN_TYPE']` should handle different plugins, their call signatures are different.

We will very soon release our new wrapping API that will come with native & MM file uploading implementation out of the box, so stay tuned.

Hope that clarifies, please DM me if needed
