### ISSUE TITLE
Add isActive property to toggle button config 

### ISSUE THREAD

**Issue by yuriibut** [wix-incubator/rich-content#86]
Add possibility to pass isActive property for plugin toolbar buttons of type `BUTTONS.TOGGLE`.

**Comment by lxgreen** [comment]
Hi

The current implementation of plugins implies that the plugin toolbar buttons state reflects the plugin  component state. E.g. the `gallery-plugin` layout drop-down selected value is the current gallery layout.

Thus, the `isActive` prop passed directly to the toolbar button contradicts this principle. Instead, the button should manage its state according to the plugin component state. The communication between plugin toolbar and plugin component is implemented with `pubsub` that exposes a `store` property. See other plugins for reference, and we are always available for questions.
