### ISSUE TITLE
Empty classes in .scss files removed from bundled css and classnames maps

### ISSUE THREAD

**Issue by BrooklynKing** [wix-incubator/rich-content#90]
If class in `.scss` is empty (https://github.com/wix-incubator/rich-content/blob/develop/packages/common/statics/styles/tooltip.scss), after build its removed from bundled css and classnames maps. Because of that you can't customize component's classNames via themes, like https://github.com/wix-incubator/rich-content/blob/develop/packages/common/src/Components/TooltipHost.jsx.

 https://github.com/wix-incubator/rich-content/blob/develop/packages/common/src/Components/TooltipHost.jsx#L9 at bundled .js `styles` is empty, and `mergeStyles` do nothings, since it operates with keys from `styles`, and classNames from `theme` not merged into result object.

**Comment by lxgreen** [comment]
temporary solution adds `outline: none` to multipleempty classes to support theming. 

commit: https://github.com/wix-incubator/rich-content/commit/77236e112dc620306b098fdba1edbbea651dfceb
